if(NOT DEFINED CPM_DOWNLOAD_VERSION)
  set(CPM_DOWNLOAD_VERSION 0.27.6)
endif()

macro(colors COLOR)
  if(NOT WIN32)
    if(${COLOR} STREQUAL "TRUE")
      string(ASCII 27 Esc)
      set(Reset "${Esc}[m")
      set(BoldRed "${Esc}[1;31m")
      set(BoldMagenta "${Esc}[1;35m")
      set(BoldYellow "${Esc}[1;33m")
      set(BoldGreen "${Esc}[1;32m")
    endif()
  endif()
endmacro()

if(CPM_SOURCE_CACHE)
  set(CPM_DOWNLOAD_LOCATION "${CPM_SOURCE_CACHE}/cpm/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
elseif(DEFINED ENV{CPM_SOURCE_CACHE})
  set(CPM_DOWNLOAD_LOCATION "$ENV{CPM_SOURCE_CACHE}/cpm/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
else()
  set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
endif()

if(NOT (EXISTS ${CPM_DOWNLOAD_LOCATION}))
  colors(TRUE)
  message("${BoldMagenta}-- Downloading CPM to ${CPM_DOWNLOAD_LOCATION} --${Reset}")
  file(DOWNLOAD "https://github.com/flagarde/CPM/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake" "${CPM_DOWNLOAD_LOCATION}")
  colors(FALSE)
endif()

include(${CPM_DOWNLOAD_LOCATION})
